config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'chat#index'
  mount ActionCable.server => '/cable'

  resources :chat do
  end


  namespace :admin do
    resources :chat, :only => [:show,:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
   has_many :messages, dependent: :destroy
   belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
   belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'



   validates :sender_id, uniqueness: { scope: :recipient_id }

   def opposed_user(user)
     user == recipient ? sender : recipient
   end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation

  after_create_commit { MessageBroadcastJob.perform_later(self) }
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages ,dependent: :destroy
  has_many :conversations, foreign_key: :sender_id ,dependent: :destroy

   # after_destroy { destroy_session }
   #
   # def destroy_session
   #   session.delete(:code)
   # end
end

app/controllers/admin/chat_controller.rb
class Admin::ChatController < ApplicationController

  def show
    cookies[:code] = User.first.code
    @user_sender = User.find_by(code:params[:id])
    @user = User.first
    @conversation = Conversation.find_by(sender_id: @user_sender.id, recipient_id: User.first)
    @message = Message.new
  end

  def create
     @conversation = Conversation.includes(:recipient).find(params[:message][:conversation])
     @message = @conversation.messages.create!(message_params)

     respond_to do |format|
       format.js
     end
  end

 private

 def message_params
   params.require(:message).permit(:user_id, :body)
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    User.find_by(code:session[:code])
  end
end

app/controllers/chat_controller.rb
require 'messagebird'
class ChatController < ApplicationController
  def index
     if !session[:code].present?
        @code = SecureRandom.hex(6)
        session[:code] = @code
        cookies[:code]= @code
        @user = User.create(code: session[:code])
        @conversation = Conversation.new(recipient: User.first, sender: @user)
        @conversation.save
     else
        @code = session[:code]
        @user = User.find_by(code: @code)
        if @user.present?
          @conversation = @user.conversations.first
        else
          session.delete(:code)
          cookies[:code]= nil
           redirect_to chat_index_path
        end
        cookies[:code] = @code
     end
  end


  def create
   @conversation = Conversation.includes(:recipient).find(params[:message][:conversation])
   # for send message
   if @conversation.messages.blank?
     require 'messagebird'
      begin
        key = 'BqAkDucda9l9SqsaNaw94LO8f'
        # Create a MessageBird client with the specified ACCESS_KEY.
        client = MessageBird::Client.new(key)
        url = 'http://localhost:3000/admin/chat/' + session[:code]
        # Send a new message.
        msg = client.message_create('Admin there', '+919033298496',url, :reference => 'Foobar')

      rescue MessageBird::ErrorException => ex
        puts
        puts 'An error occured while requesting a Message object:'
        puts

        ex.errors.each do |error|
          puts "  code        : #{error.code}"
          puts "  description : #{error.description}"
          puts "  parameter   : #{error.parameter}"
          puts
        end
      end
   end
   @message = @conversation.messages.create!(message_params)
   respond_to do |format|
     format.js
   end
 end

 private

  def message_params
    params.require(:message).permit(:user_id, :body)
  end

end

app/helpers/admin/chat_helper.rb
module Admin::ChatHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    User.find_by(code:session[:code])
  end
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/views/admin/chat/_message.html.erb
<li class="left clearfix">
  <span class="chat-img pull-right">
    <img src="http://placehold.it/50/FA6F57/fff&text=ME" alt="User Avatar" class="img-circle" />
  </span>
  <div class="chat-body clearfix">
      <p class="text-right"><%= message.body %></p>
  </div>
</li>

app/views/admin/chat/_receiver_message.html.erb
<li class="right clearfix">
  <span class="chat-img pull-left">
    <img src="http://placehold.it/50/55C1E7/fff&text=U" alt="User Avatar" class="img-circle" />
  </span>
  <div class="chat-body clearfix">
      <!-- <div class="header">
          <strong class="primary-font"><%= user.code %></strong>
          <small class="text-muted text-right">
            <span class="fa fa-times pull-left"></span>14 mins ago
          </small>
      </div> -->
      <p>
        <%= message.body %>
      </p>
  </div>
</li>

app/views/admin/chat/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-5">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-comment"></span> Chat
                </div>
                <div class="panel-body">
                    <ul class="chat">


                        <li class="left clearfix">
                          <span class="chat-img pull-left">
                            <img src="http://placehold.it/50/55C1E7/fff&text=U" alt="User Avatar" class="img-circle" />
                          </span>

                            <div class="chat-body clearfix">
                                <div class="header">
                                    <strong class="primary-font">Jack Sparrow</strong> <small class="pull-right text-muted">
                                        <span class="glyphicon glyphicon-time"></span>14 mins ago</small>
                                </div>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare
                                    dolor, quis ullamcorper ligula sodales.
                                </p>
                            </div>
                        </li>
                        <li class="right clearfix"><span class="chat-img pull-right">
                            <img src="http://placehold.it/50/FA6F57/fff&text=ME" alt="User Avatar" class="img-circle" />
                        </span>
                            <div class="chat-body clearfix">
                                <div class="header">
                                    <small class=" text-muted"><span class="glyphicon glyphicon-time"></span>15 mins ago</small>
                                    <strong class="pull-right primary-font">Bhaumik Patel</strong>
                                </div>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare
                                    dolor, quis ullamcorper ligula sodales.
                                </p>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="panel-footer">
                    <div class="input-group">
                        <input id="btn-input" type="text" class="form-control input-sm" placeholder="Type your message here..." />
                        <span class="input-group-btn">
                            <button class="btn btn-warning btn-sm" id="btn-chat">
                                Send</button>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admin/chat/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="panel panel-primary">
                <div class="heading">
                    <span class="glyphicon glyphicon-comment"></span> Chat
                    <%= @code %>
                </div>
                <div class="panel-body">
                  <ul class="chat" id="conversation" data-id = "<%= @conversation.id %>">
                    <% @conversation.messages.each do |message|%>
                      <% if  message.user_id == User.first.id %>
                        <%= render :partial => 'chat/message', :locals => {message: message, user: message.user} %>
                      <% else %>
                        <%= render :partial => 'chat/receiver_message', :locals => {message: message, user: message.user} %>
                      <% end %>
                    <% end %>
                  </ul>
                </div>
                <div class="panel-footer">
                    <div class="input-group">
                        <%= form_for @message, :url => admin_chat_index_path,:authenticity_token => true, remote: true, class: 'form_submit' do |f| %>
                        <%= f.hidden_field :conversation, value: @conversation.id %>
                        <%= f.hidden_field :user_id, value: @user.id %>

                        <%= f.text_area :body, class: "form-control input-sm",placeholder: "Type your message here..." %>
                        <%= f.submit "Send", class: "btn btn-warning btn-sm" %>
                      <% end %>
                        <!-- <input id="btn-input" type="text" class="form-control input-sm" placeholder="Type your message here..." />
                        <span class="input-group-btn">
                            <button class="btn btn-warning btn-sm" id="btn-chat">
                                Send</button>
                        </span> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>

</script>

app/views/chat/_message.html.erb
<li class="right clearfix">
  <span class="chat-img pull-right">
    <img src="http://placehold.it/50/FA6F57/fff&text=ME" alt="User Avatar" class="img-circle" />
  </span>
  <div class="chat-body clearfix">
      <p class="text-right"><%= message.body %></p>
  </div>
</li>

app/views/chat/_receiver_message.html.erb
<li class="left clearfix">
  <span class="chat-img pull-left">
    <img src="http://placehold.it/50/55C1E7/fff&text=U" alt="User Avatar" class="img-circle" />
  </span>
  <div class="chat-body clearfix">
      <p>
        <%= message.body %>
      </p>
  </div>
</li>

app/views/chat/index.html.erb
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="chat-main">
  <div class="heading">
      Chat <%= @code %>
      <span class="right-icon">
        <i class="fa fa-minus"></i>
        <i class="fa fa-plus"></i>
      </span>
  </div>

  <div class="chat-content">
    <ul class="chat" id="conversation" data-id = "<%= @conversation.id %>">
      <% @conversation.messages.each do |message|%>
        <% if  message.user_id == current_user.id %>
          <%= render :partial => 'chat/message', :locals => {message: message, user: message.user} %>
        <% else %>
          <%= render :partial => 'chat/receiver_message', :locals => {message: message, user: message.user} %>
        <% end %>
      <% end %>
    </ul>

    <div class="form-textarea">
      <%= form_for Message.new, url: {action: "create"},:authenticity_token => true, remote: true, class: 'form_submit' do |f| %>
        <%= f.hidden_field :conversation, value: @conversation.id %>
        <%= f.hidden_field :user_id, value: @user.id %>

        <%= f.text_area :body, class: "form-control input-sm",placeholder: "Type your message here..." %>
        <%= f.submit "Send", class: "btn btn-warning btn-sm" %>
      <% end %>
    </div>
  </div>
</div>



<script>
  $( document ).ready(function() {
    $('.heading').click(function(){
      $(this).next().slideToggle('show');
      $(this).toggleClass('show');
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>